### ISSUE TITLE
Add Megalovania Melody

### ISSUE THREAD

**Issue by YTKacperSKY** [TU-DO-Makerspace/Wireless-Doorbell#1]

**Comment by CTXz** [comment]
Added with a6433c735dc64febe1e0a09d0242fba3e94a3ebc, eed7b37d6098040237aac8aa1f592307dd3968aa, 31db9d916fd02fc33326f1a32433b87158fa364f, e5858d2dc754797ef4cf0278fe4d5d13eb757b08, 2b8b0a116cfedb872fc563dcf3bbdf282c8a211e :)
